name=CircuitDigestCloud
version=1.0.0
author=Jobit Joseph, Circuit Digest
maintainer=Jobit Joseph <jobitjoseph1@gmail.com>
sentence=Arduino client for the CircuitDigest Cloud MQTT platform.
paragraph=Arduino client for the CircuitDigest Cloud MQTT platform.
category=Communication
url=https://github.com/circuitdigest/CircuitDigestCloud
architectures=*
depends=PubSubClient
includes=CircuitDigestCloud.h
