name=CircuitDigestCloud
version=1.0.2
author=Jobit Joseph, Circuit Digest
maintainer=Jobit Joseph <jobitjoseph1@gmail.com>
sentence=Arduino client for the CircuitDigest Cloud MQTT platform.
paragraph=MQTT wrapper for CircuitDigest Cloud.Works with ESP32, ESP8266, RP2040, SAMD, nRF52, and any board that provides an Arduino Client transport.
category=Communication
url=https://github.com/Circuit-Digest/CircuitDigestCloud
architectures=*
depends=PubSubClient
includes=CircuitDigestCloud.h

